config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :class_types
  resources :subjects
  resources :rooms
  resources :teachers
  devise_for :users
  resources :users

  root 'groups#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_and_belongs_to_many :rooms
	has_and_belongs_to_many :subjects
	has_and_belongs_to_many :teachers
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:number, :direction)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification
  .form-inputs
    = f.input :number
    = f.input :direction
    = f.association :rooms, label_method: :number, value_method: :id

  .form-actions
    = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
%h1 Listing groups

%table
  %thead
    %tr
      %th Number
      %th Direction
      %th
      %th
      %th

  %tbody
    - @groups.each do |group|
      %tr
        %td= group.number
        %td= group.direction
        %td= link_to 'Show', group
        %td= link_to 'Edit', edit_group_path(group)
        %td= link_to 'Destroy', group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @group.number
%p
  %b Direction:
  = @group.direction

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path